version: "3.9"

services:
  application:
    build:
      dockerfile: ./Dockerfile
    environment:
      FLASK_APP: main
      CONFIG: ProductionConfig
      SQLALCHEMY_DATABASE_URI: postgresql://username:passwd!@pg:5432/library
    ports:
      - "8000:80"
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd!
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
